vich_uploader:
  db_driver: orm
  metadata:
    type: attribute

  mappings:
    products:
      uri_prefix: uploads/imgs/products
      upload_destination: "%kernel.project_dir%/public/uploads/imgs/products"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

    profils:
      uri_prefix: uploads/imgs/profils
      upload_destination: "%kernel.project_dir%/public/uploads/imgs/profils"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

      inject_on_load: false
      delete_on_update: true
      delete_on_remove: true
